### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JustCauseWhyNot** [eemmy/Reshade2Basalt#4]
```
❯ python3 run.py --preset=./thermals/Drag\ and\ drop\ the\ contents\ of\ this\ folder\ into\ your\ game\ directory/ReShade.ini
Cloning into '/home/justcausewhynot/.local/bin/Reshade2Basalt/.temp/shaders'...
remote: Enumerating objects: 5168, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 5168 (delta 52), reused 81 (delta 33), pack-reused 5058
Receiving objects: 100% (5168/5168), 51.19 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (3336/3336), done.
error: pathspec 'master' did not match any file(s) known to git
Traceback (most recent call last):
  File "/home/justcausewhynot/.local/bin/Reshade2Basalt/run.py", line 34, in <module>
    settings = files.get_preset_ini(shell.get_arg(preset))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/justcausewhynot/.local/bin/Reshade2Basalt/files.py", line 77, in get_preset_ini
    effects = file_contents.split("Techniques=")[1].split("TechniqueSorting=")[0].replace(" ", "").replace("\n", "").split(",")
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by AlphaCraft9658** [comment]
I'm also getting an index out of range error, but at a different place in the script.
